config/routes.rb
JobBoard::Application.routes.draw do
  resources :messages


  resources :job_postings


  resources :companies


  devise_for :users, controllers: { confirmations: 'confirmations' }
  devise_scope :user do
    get '/confirmation-getting-started' => 'registrations#getting_started', as: 'confirmation_getting_started'
  end

  resources :users

  root :to => 'job_postings#index'

end

app/models/job_posting.rb
class JobPosting < ActiveRecord::Base
  belongs_to :user
  belongs_to :company
  attr_accessible :description, :location, :title
end

app/controllers/job_postings_controller.rb
class JobPostingsController < ApplicationController
  # GET /job_postings
  # GET /job_postings.json
  def index
    @job_postings = JobPosting.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @job_postings }
    end
  end

  # GET /job_postings/1
  # GET /job_postings/1.json
  def show
    @job_posting = JobPosting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job_posting }
    end
  end

  # GET /job_postings/new
  # GET /job_postings/new.json
  def new
    @job_posting = JobPosting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job_posting }
    end
  end

  # GET /job_postings/1/edit
  def edit
    @job_posting = JobPosting.find(params[:id])
  end

  # POST /job_postings
  # POST /job_postings.json
  def create
    @company = Company.find_or_create_by_name(params[:job_posting][:company])
    params[:job_posting].delete(:company)
    @job_posting = JobPosting.new(params[:job_posting])
    @job_posting.company = @company

    respond_to do |format|
      if @job_posting.save
        if @company.description.nil?
          format.html { redirect_to edit_company_path(@company), notice: "This company doesn't currently have a description. Add one if you'd like."}
          format.json { render json: @job_posting, status: :created, location: @job_posting }
        else
          format.html { redirect_to @job_posting, notice: 'Job posting was successfully created.' }
          format.json { render json: @job_posting, status: :created, location: @job_posting }
        end
      else
        format.html { render action: "new" }
        format.json { render json: @job_posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /job_postings/1
  # PUT /job_postings/1.json
  def update
    @job_posting = JobPosting.find(params[:id])

    respond_to do |format|
      if @job_posting.update_attributes(params[:job_posting])
        format.html { redirect_to @job_posting, notice: 'Job posting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job_posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_postings/1
  # DELETE /job_postings/1.json
  def destroy
    @job_posting = JobPosting.find(params[:id])
    @job_posting.destroy

    respond_to do |format|
      format.html { redirect_to job_postings_url }
      format.json { head :no_content }
    end
  end
end

app/views/job_postings/_form.html.erb
<%= form_for(@job_posting) do |f| %>
  <% if @job_posting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job_posting.errors.count, "error") %> prohibited this job_posting from being saved:</h2>

      <ul>
      <% @job_posting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/job_postings/_single_entry.html.erb
<div class="job_posting_entry panel" id="<%= @job_posting.id %>"  onclick="location.href='<%= job_posting_path(@job_posting) %>';"  style="cursor:pointer;">
  <%# image_tag 'up_arrow.png' %>
  <h4 class="subheader"><%= @job_posting.title %> <b>at</b> <%= link_to @job_posting.company.name, @job_posting.company %></h4>
  <h6 class="subheader">Posted by <%= link_to 'Josh Wilson', @job_posting.user %></h6>
</div>

app/views/job_postings/edit.html.erb
<h1>Editing job_posting</h1>

<%= render 'form' %>

<%= link_to 'Show', @job_posting %> |
<%= link_to 'Back', job_postings_path %>

app/views/job_postings/index.html.erb
<h1>Job Postings</h1>

<% @job_postings.each do |job_posting| %>
  <% @job_posting = job_posting %>
  <%= render 'single_entry' %>
<% end %>

<%= paginate @job_postings %>

<br />

<%= link_to 'New Job posting', new_job_posting_path %>

app/views/job_postings/new.html.erb
<h1>New job_posting</h1>

<%= render 'form' %>

<%= link_to 'Back', job_postings_path %>

app/views/job_postings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @job_posting.user %>
</p>

<p>
  <b>Company:</b>
  <%= @job_posting.company %>
</p>

<p>
  <b>Title:</b>
  <%= @job_posting.title %>
</p>

<p>
  <b>Location:</b>
  <%= @job_posting.location %>
</p>

<p>
  <b>Description:</b>
  <%= @job_posting.description %>
</p>


<%= link_to 'Edit', edit_job_posting_path(@job_posting) %> |
<%= link_to 'Back', job_postings_path %>